version: '3.7'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test_admin_user"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql:/var/lib/mysql
      - /home/szangiev/hw_db:/dump
    ports:
      - "3306:3306"
